//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram")]

namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	/// <summary>
	/// DomainClass GVSJGGGASLProyectoIPSDiagram
	/// Description for UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram.DisplayName", typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel), "UPM_IPS.GVSJGGGASLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram.Description", typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel), "UPM_IPS.GVSJGGGASLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e09f687d-90fb-4042-95cd-cd546b6213c7")]
	public partial class GVSJGGGASLProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaPrincipal)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaPrincipal newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaPrincipal(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaSecundaria newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaSecundaria(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenu newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenu(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemMenu newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemMenu(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoFin)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaEstadoFin newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaEstadoFin(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneBotons)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaTieneBotons newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaTieneBotons(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneMenus)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaTieneMenus newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaTieneMenus(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_Fin)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton_Fin newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton_Fin(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_Ventana)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton_Ventana newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton_Ventana(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuTieneItemsMenu)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenuTieneItemMenus newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenuTieneItemMenus(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_EstadoFin)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemMenu_EstadoFin newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemMenu_EstadoFin(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_Ventana)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemMenu_Ventana newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemMenu_Ventana(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaPrincipal.DecoratorsInitialized += MetaforaVentanaPrincipalDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaSecundaria.DecoratorsInitialized += MetaforaVentanaSecundariaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton.DecoratorsInitialized += MetaforaBotonDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenu.DecoratorsInitialized += MetaforaMenuDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemMenu.DecoratorsInitialized += MetaforaItemMenuDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaVentanaPrincipal.
		/// </summary>
		internal static partial class MetaforaVentanaPrincipalDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaVentanaPrincipal.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaVentanaSecundaria.
		/// </summary>
		internal static partial class MetaforaVentanaSecundariaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaVentanaSecundaria.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaBoton.
		/// </summary>
		internal static partial class MetaforaBotonDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaBoton.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaMenu.
		/// </summary>
		internal static partial class MetaforaMenuDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaMenu.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaItemMenu.
		/// </summary>
		internal static partial class MetaforaItemMenuDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaItemMenu.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneBotonsToolConnectAction ventanaTieneBotonsToolConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneMenusToolConnectAction ventanaTieneMenusToolConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_FinToolConnectAction boton_FinToolConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_VentanaToolConnectAction boton_VentanaToolConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuTieneItemsMenuToolConnectAction menuTieneItemsMenuToolConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_EstadoFinToolConnectAction itemMenu_EstadoFinToolConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_VentanaToolConnectAction itemMenu_VentanaToolConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.VentanaTieneBotonsToolFilterString))
				{
					if (this.ventanaTieneBotonsToolConnectAction == null)
					{
						this.ventanaTieneBotonsToolConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneBotonsToolConnectAction(this);
						this.ventanaTieneBotonsToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.ventanaTieneBotonsToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.VentanaTieneMenusToolFilterString))
				{
					if (this.ventanaTieneMenusToolConnectAction == null)
					{
						this.ventanaTieneMenusToolConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneMenusToolConnectAction(this);
						this.ventanaTieneMenusToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.ventanaTieneMenusToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.Boton_FinToolFilterString))
				{
					if (this.boton_FinToolConnectAction == null)
					{
						this.boton_FinToolConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_FinToolConnectAction(this);
						this.boton_FinToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.boton_FinToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.Boton_VentanaToolFilterString))
				{
					if (this.boton_VentanaToolConnectAction == null)
					{
						this.boton_VentanaToolConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_VentanaToolConnectAction(this);
						this.boton_VentanaToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.boton_VentanaToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.MenuTieneItemsMenuToolFilterString))
				{
					if (this.menuTieneItemsMenuToolConnectAction == null)
					{
						this.menuTieneItemsMenuToolConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuTieneItemsMenuToolConnectAction(this);
						this.menuTieneItemsMenuToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.menuTieneItemsMenuToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.ItemMenu_EstadoFinToolFilterString))
				{
					if (this.itemMenu_EstadoFinToolConnectAction == null)
					{
						this.itemMenu_EstadoFinToolConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_EstadoFinToolConnectAction(this);
						this.itemMenu_EstadoFinToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.itemMenu_EstadoFinToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.ItemMenu_VentanaToolFilterString))
				{
					if (this.itemMenu_VentanaToolConnectAction == null)
					{
						this.itemMenu_VentanaToolConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_VentanaToolConnectAction(this);
						this.itemMenu_VentanaToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.itemMenu_VentanaToolConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.ventanaTieneBotonsToolConnectAction != null)
					{
						this.ventanaTieneBotonsToolConnectAction.Dispose();
						this.ventanaTieneBotonsToolConnectAction = null;
					}
					if(this.ventanaTieneMenusToolConnectAction != null)
					{
						this.ventanaTieneMenusToolConnectAction.Dispose();
						this.ventanaTieneMenusToolConnectAction = null;
					}
					if(this.boton_FinToolConnectAction != null)
					{
						this.boton_FinToolConnectAction.Dispose();
						this.boton_FinToolConnectAction = null;
					}
					if(this.boton_VentanaToolConnectAction != null)
					{
						this.boton_VentanaToolConnectAction.Dispose();
						this.boton_VentanaToolConnectAction = null;
					}
					if(this.menuTieneItemsMenuToolConnectAction != null)
					{
						this.menuTieneItemsMenuToolConnectAction.Dispose();
						this.menuTieneItemsMenuToolConnectAction = null;
					}
					if(this.itemMenu_EstadoFinToolConnectAction != null)
					{
						this.itemMenu_EstadoFinToolConnectAction.Dispose();
						this.itemMenu_EstadoFinToolConnectAction = null;
					}
					if(this.itemMenu_VentanaToolConnectAction != null)
					{
						this.itemMenu_VentanaToolConnectAction.Dispose();
						this.itemMenu_VentanaToolConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// GVSJGGGASLProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe09f687d, 0x90fb, 0x4042, 0x95, 0xcd, 0xcd, 0x54, 0x6b, 0x62, 0x13, 0xc7);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public GVSJGGGASLProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public GVSJGGGASLProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaPrincipal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneBotons), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneMenus), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_Fin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_Ventana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuTieneItemsMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_EstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_Ventana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaPrincipal)
				{
					parentElement = GetParentForVentanaPrincipal((global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaPrincipal)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria)
				{
					parentElement = GetParentForVentanaSecundaria((global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton)
				{
					parentElement = GetParentForBoton((global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu)
				{
					parentElement = GetParentForMenu((global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu)
				{
					parentElement = GetParentForItemMenu((global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoFin)
				{
					parentElement = GetParentForEstadoFin((global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoFin)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForVentanaPrincipal( global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaPrincipal root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForVentanaSecundaria( global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForBoton( global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForMenu( global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForItemMenu( global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForEstadoFin( global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoFin root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneBotons), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaTieneMenus), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_Fin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton_Ventana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuTieneItemsMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_EstadoFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemMenu_Ventana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram diagram = linkShape.Diagram as global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
