//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram")]

namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	/// <summary>
	/// DomainClass GVSJGGGASLProyectoIPSDiagram
	/// Description for UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram.DisplayName", typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel), "UPM_IPS.GVSJGGGASLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram.Description", typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel), "UPM_IPS.GVSJGGGASLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("733b6c84-76a7-46e2-bd48-812783e66985")]
	public partial class GVSJGGGASLProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaSecundaria newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaSecundaria(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaPrincipal newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaPrincipal(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoDeFin)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaEstadoDeFin newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaEstadoDeFin(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemsMenu)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemsMenu newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemsMenu(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenu newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenu(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaReferencesBoton)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVN_BT newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVN_BT(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaReferencesMenu)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVN_MN newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVN_MN(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeFinalizacionB)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBT_EF newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBT_EF(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeAccionB)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBT_VN newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBT_VN(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuReferencesItemsMenu)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMN_IM newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMN_IM(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeFinalizacionM)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaIM_EF newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaIM_EF(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeAccionM)
			{
				global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaIM_VN newShape = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaIM_VN(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaSecundaria.DecoratorsInitialized += MetaforaVentanaSecundariaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaVentanaPrincipal.DecoratorsInitialized += MetaforaVentanaPrincipalDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaItemsMenu.DecoratorsInitialized += MetaforaItemsMenuDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaMenu.DecoratorsInitialized += MetaforaMenuDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.GVSJGGGASLProyectoIPS.MetaforaBoton.DecoratorsInitialized += MetaforaBotonDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaVentanaSecundaria.
		/// </summary>
		internal static partial class MetaforaVentanaSecundariaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaVentanaSecundaria.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaVentanaPrincipal.
		/// </summary>
		internal static partial class MetaforaVentanaPrincipalDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaVentanaPrincipal.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaItemsMenu.
		/// </summary>
		internal static partial class MetaforaItemsMenuDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaItemsMenu.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemsMenu.tituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tiuloDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaMenu.
		/// </summary>
		internal static partial class MetaforaMenuDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaMenu.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu.tituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tituloDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaBoton.
		/// </summary>
		internal static partial class MetaforaBotonDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaBoton.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton.tituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tituloDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.VN_BTtConnectAction vN_BTtConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.VN_MNtConnectAction vN_MNtConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.BT_EFtConnectAction bT_EFtConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.AccionBotontConnectAction accionBotontConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.MN_IMtConnectAction mN_IMtConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.FinalizacionMtConnectAction finalizacionMtConnectAction;
		private global::UPM_IPS.GVSJGGGASLProyectoIPS.AccionMtConnectAction accionMtConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.VN_BTtFilterString))
				{
					if (this.vN_BTtConnectAction == null)
					{
						this.vN_BTtConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.VN_BTtConnectAction(this);
						this.vN_BTtConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.vN_BTtConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.VN_MNtFilterString))
				{
					if (this.vN_MNtConnectAction == null)
					{
						this.vN_MNtConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.VN_MNtConnectAction(this);
						this.vN_MNtConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.vN_MNtConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.BT_EFtFilterString))
				{
					if (this.bT_EFtConnectAction == null)
					{
						this.bT_EFtConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.BT_EFtConnectAction(this);
						this.bT_EFtConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.bT_EFtConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.AccionBotontFilterString))
				{
					if (this.accionBotontConnectAction == null)
					{
						this.accionBotontConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.AccionBotontConnectAction(this);
						this.accionBotontConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.accionBotontConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.MN_IMtFilterString))
				{
					if (this.mN_IMtConnectAction == null)
					{
						this.mN_IMtConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.MN_IMtConnectAction(this);
						this.mN_IMtConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.mN_IMtConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.FinalizacionMtFilterString))
				{
					if (this.finalizacionMtConnectAction == null)
					{
						this.finalizacionMtConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.FinalizacionMtConnectAction(this);
						this.finalizacionMtConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.finalizacionMtConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSToolboxHelper.AccionMtFilterString))
				{
					if (this.accionMtConnectAction == null)
					{
						this.accionMtConnectAction = new global::UPM_IPS.GVSJGGGASLProyectoIPS.AccionMtConnectAction(this);
						this.accionMtConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.accionMtConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.vN_BTtConnectAction != null)
					{
						this.vN_BTtConnectAction.Dispose();
						this.vN_BTtConnectAction = null;
					}
					if(this.vN_MNtConnectAction != null)
					{
						this.vN_MNtConnectAction.Dispose();
						this.vN_MNtConnectAction = null;
					}
					if(this.bT_EFtConnectAction != null)
					{
						this.bT_EFtConnectAction.Dispose();
						this.bT_EFtConnectAction = null;
					}
					if(this.accionBotontConnectAction != null)
					{
						this.accionBotontConnectAction.Dispose();
						this.accionBotontConnectAction = null;
					}
					if(this.mN_IMtConnectAction != null)
					{
						this.mN_IMtConnectAction.Dispose();
						this.mN_IMtConnectAction = null;
					}
					if(this.finalizacionMtConnectAction != null)
					{
						this.finalizacionMtConnectAction.Dispose();
						this.finalizacionMtConnectAction = null;
					}
					if(this.accionMtConnectAction != null)
					{
						this.accionMtConnectAction.Dispose();
						this.accionMtConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// GVSJGGGASLProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x733b6c84, 0x76a7, 0x46e2, 0xbd, 0x48, 0x81, 0x27, 0x83, 0xe6, 0x69, 0x85);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public GVSJGGGASLProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public GVSJGGGASLProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoDeFin), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemsMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaReferencesBoton), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaReferencesMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeFinalizacionB), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeAccionB), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuReferencesItemsMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeFinalizacionM), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeAccionM), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria)
				{
					parentElement = GetParentForVentanaSecundaria((global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaSecundaria)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana)
				{
					parentElement = GetParentForVentana((global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoDeFin)
				{
					parentElement = GetParentForEstadoDeFin((global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoDeFin)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemsMenu)
				{
					parentElement = GetParentForItemsMenu((global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemsMenu)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu)
				{
					parentElement = GetParentForMenu((global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu)childElement);
				} else
				if(childElement is global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton)
				{
					parentElement = GetParentForBoton((global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForVentanaSecundaria( global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForVentana( global::UPM_IPS.GVSJGGGASLProyectoIPS.Ventana root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForEstadoDeFin( global::UPM_IPS.GVSJGGGASLProyectoIPS.EstadoDeFin root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForItemsMenu( global::UPM_IPS.GVSJGGGASLProyectoIPS.ItemsMenu root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForMenu( global::UPM_IPS.GVSJGGGASLProyectoIPS.Menu root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz GetParentForBoton( global::UPM_IPS.GVSJGGGASLProyectoIPS.Boton root )
			{
				// Segments 0 and 1
				global::UPM_IPS.GVSJGGGASLProyectoIPS.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaReferencesBoton), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.VentanaReferencesMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeFinalizacionB), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeAccionB), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.MenuReferencesItemsMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeFinalizacionM), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.RelacionDeAccionM), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram diagram = linkShape.Diagram as global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
