//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	/// <summary>
	/// DomainModel GVSJGGGASLProyectoIPSDomainModel
	/// Description for UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel), "UPM_IPS.GVSJGGGASLProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel), "UPM_IPS.GVSJGGGASLProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("ca1755fc-0c8c-42cd-b132-e52f5c66b3b0")]
	public partial class GVSJGGGASLProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// GVSJGGGASLProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xca1755fc, 0x0c8c, 0x42cd, 0xb1, 0x32, 0xe5, 0x2f, 0x5c, 0x66, 0xb3, 0xb0);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public GVSJGGGASLProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Tapiz),
				typeof(Ventana),
				typeof(VentanaSecundaria),
				typeof(VentanaPrincipal),
				typeof(Menu),
				typeof(ItemsMenu),
				typeof(Boton),
				typeof(EstadoDeFin),
				typeof(TapizHasVentana),
				typeof(RelacionDeFinalizacionB),
				typeof(TapizHasEstadoDeFin),
				typeof(RelacionDeFinalizacionM),
				typeof(RelacionDeAccionM),
				typeof(RelacionDeAccionB),
				typeof(TapizHasBoton),
				typeof(TapizHasMenu),
				typeof(TapizHasItemsMenu),
				typeof(MenuReferencesItemsMenu),
				typeof(VentanaReferencesBoton),
				typeof(VentanaReferencesMenu),
				typeof(GVSJGGGASLProyectoIPSDiagram),
				typeof(MetaforaVN_BT),
				typeof(MetaforaVN_MN),
				typeof(MetaforaBT_EF),
				typeof(MetaforaMN_IM),
				typeof(MetaforaIM_EF),
				typeof(MetaforaIM_VN),
				typeof(MetaforaBT_VN),
				typeof(MetaforaVentanaPrincipal),
				typeof(MetaforaVentanaSecundaria),
				typeof(MetaforaMenu),
				typeof(MetaforaItemsMenu),
				typeof(MetaforaBoton),
				typeof(MetaforaEstadoDeFin),
				typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Ventana), "nombre", Ventana.nombreDomainPropertyId, typeof(Ventana.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "ancho", Ventana.anchoDomainPropertyId, typeof(Ventana.anchoPropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "alto", Ventana.altoDomainPropertyId, typeof(Ventana.altoPropertyHandler)),
				new DomainMemberInfo(typeof(VentanaSecundaria), "padrePid", VentanaSecundaria.padrePidDomainPropertyId, typeof(VentanaSecundaria.padrePidPropertyHandler)),
				new DomainMemberInfo(typeof(VentanaSecundaria), "modal", VentanaSecundaria.modalDomainPropertyId, typeof(VentanaSecundaria.modalPropertyHandler)),
				new DomainMemberInfo(typeof(Menu), "titulo", Menu.tituloDomainPropertyId, typeof(Menu.tituloPropertyHandler)),
				new DomainMemberInfo(typeof(ItemsMenu), "titulo", ItemsMenu.tituloDomainPropertyId, typeof(ItemsMenu.tituloPropertyHandler)),
				new DomainMemberInfo(typeof(Boton), "titulo", Boton.tituloDomainPropertyId, typeof(Boton.tituloPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizHasVentana), "Tapiz", TapizHasVentana.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasVentana), "Ventana", TapizHasVentana.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeFinalizacionB), "Boton", RelacionDeFinalizacionB.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeFinalizacionB), "EstadoDeFin", RelacionDeFinalizacionB.EstadoDeFinDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstadoDeFin), "Tapiz", TapizHasEstadoDeFin.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstadoDeFin), "EstadoDeFin", TapizHasEstadoDeFin.EstadoDeFinDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeFinalizacionM), "ItemsMenu", RelacionDeFinalizacionM.ItemsMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeFinalizacionM), "EstadoDeFin", RelacionDeFinalizacionM.EstadoDeFinDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeAccionM), "ItemsMenu", RelacionDeAccionM.ItemsMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeAccionM), "Ventana", RelacionDeAccionM.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeAccionB), "Boton", RelacionDeAccionB.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDeAccionB), "Ventana", RelacionDeAccionB.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasBoton), "Tapiz", TapizHasBoton.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasBoton), "Boton", TapizHasBoton.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasMenu), "Tapiz", TapizHasMenu.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasMenu), "Menu", TapizHasMenu.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasItemsMenu), "Tapiz", TapizHasItemsMenu.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasItemsMenu), "ItemsMenu", TapizHasItemsMenu.ItemsMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(MenuReferencesItemsMenu), "Menu", MenuReferencesItemsMenu.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(MenuReferencesItemsMenu), "ItemsMenu", MenuReferencesItemsMenu.ItemsMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaReferencesBoton), "Ventana", VentanaReferencesBoton.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaReferencesBoton), "Boton", VentanaReferencesBoton.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaReferencesMenu), "Ventana", VentanaReferencesMenu.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaReferencesMenu), "Menu", VentanaReferencesMenu.MenuDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(22);
				createElementMap.Add(typeof(Tapiz), 0);
				createElementMap.Add(typeof(VentanaSecundaria), 1);
				createElementMap.Add(typeof(VentanaPrincipal), 2);
				createElementMap.Add(typeof(Menu), 3);
				createElementMap.Add(typeof(ItemsMenu), 4);
				createElementMap.Add(typeof(Boton), 5);
				createElementMap.Add(typeof(EstadoDeFin), 6);
				createElementMap.Add(typeof(GVSJGGGASLProyectoIPSDiagram), 7);
				createElementMap.Add(typeof(MetaforaVN_BT), 8);
				createElementMap.Add(typeof(MetaforaVN_MN), 9);
				createElementMap.Add(typeof(MetaforaBT_EF), 10);
				createElementMap.Add(typeof(MetaforaMN_IM), 11);
				createElementMap.Add(typeof(MetaforaIM_EF), 12);
				createElementMap.Add(typeof(MetaforaIM_VN), 13);
				createElementMap.Add(typeof(MetaforaBT_VN), 14);
				createElementMap.Add(typeof(MetaforaVentanaPrincipal), 15);
				createElementMap.Add(typeof(MetaforaVentanaSecundaria), 16);
				createElementMap.Add(typeof(MetaforaMenu), 17);
				createElementMap.Add(typeof(MetaforaItemsMenu), 18);
				createElementMap.Add(typeof(MetaforaBoton), 19);
				createElementMap.Add(typeof(MetaforaEstadoDeFin), 20);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Tapiz(partition, propertyAssignments);
				case 1: return new VentanaSecundaria(partition, propertyAssignments);
				case 2: return new VentanaPrincipal(partition, propertyAssignments);
				case 3: return new Menu(partition, propertyAssignments);
				case 4: return new ItemsMenu(partition, propertyAssignments);
				case 5: return new Boton(partition, propertyAssignments);
				case 6: return new EstadoDeFin(partition, propertyAssignments);
				case 7: return new GVSJGGGASLProyectoIPSDiagram(partition, propertyAssignments);
				case 8: return new MetaforaVN_BT(partition, propertyAssignments);
				case 9: return new MetaforaVN_MN(partition, propertyAssignments);
				case 10: return new MetaforaBT_EF(partition, propertyAssignments);
				case 11: return new MetaforaMN_IM(partition, propertyAssignments);
				case 12: return new MetaforaIM_EF(partition, propertyAssignments);
				case 13: return new MetaforaIM_VN(partition, propertyAssignments);
				case 14: return new MetaforaBT_VN(partition, propertyAssignments);
				case 15: return new MetaforaVentanaPrincipal(partition, propertyAssignments);
				case 16: return new MetaforaVentanaSecundaria(partition, propertyAssignments);
				case 17: return new MetaforaMenu(partition, propertyAssignments);
				case 18: return new MetaforaItemsMenu(partition, propertyAssignments);
				case 19: return new MetaforaBoton(partition, propertyAssignments);
				case 20: return new MetaforaEstadoDeFin(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(12);
				createElementLinkMap.Add(typeof(TapizHasVentana), 0);
				createElementLinkMap.Add(typeof(RelacionDeFinalizacionB), 1);
				createElementLinkMap.Add(typeof(TapizHasEstadoDeFin), 2);
				createElementLinkMap.Add(typeof(RelacionDeFinalizacionM), 3);
				createElementLinkMap.Add(typeof(RelacionDeAccionM), 4);
				createElementLinkMap.Add(typeof(RelacionDeAccionB), 5);
				createElementLinkMap.Add(typeof(TapizHasBoton), 6);
				createElementLinkMap.Add(typeof(TapizHasMenu), 7);
				createElementLinkMap.Add(typeof(TapizHasItemsMenu), 8);
				createElementLinkMap.Add(typeof(MenuReferencesItemsMenu), 9);
				createElementLinkMap.Add(typeof(VentanaReferencesBoton), 10);
				createElementLinkMap.Add(typeof(VentanaReferencesMenu), 11);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.GVSJGGGASLProyectoIPS.GVSJGGGASLProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizHasVentana(partition, roleAssignments, propertyAssignments);
				case 1: return new RelacionDeFinalizacionB(partition, roleAssignments, propertyAssignments);
				case 2: return new TapizHasEstadoDeFin(partition, roleAssignments, propertyAssignments);
				case 3: return new RelacionDeFinalizacionM(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionDeAccionM(partition, roleAssignments, propertyAssignments);
				case 5: return new RelacionDeAccionB(partition, roleAssignments, propertyAssignments);
				case 6: return new TapizHasBoton(partition, roleAssignments, propertyAssignments);
				case 7: return new TapizHasMenu(partition, roleAssignments, propertyAssignments);
				case 8: return new TapizHasItemsMenu(partition, roleAssignments, propertyAssignments);
				case 9: return new MenuReferencesItemsMenu(partition, roleAssignments, propertyAssignments);
				case 10: return new VentanaReferencesBoton(partition, roleAssignments, propertyAssignments);
				case 11: return new VentanaReferencesMenu(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.GVSJGGGASLProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GVSJGGGASLProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (GVSJGGGASLProyectoIPSDomainModel.resourceManager == null)
				{
					GVSJGGGASLProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(GVSJGGGASLProyectoIPSDomainModel).Assembly);
				}
				return GVSJGGGASLProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return GVSJGGGASLProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return GVSJGGGASLProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (GVSJGGGASLProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new GVSJGGGASLProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					GVSJGGGASLProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return GVSJGGGASLProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (GVSJGGGASLProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new GVSJGGGASLProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					GVSJGGGASLProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return GVSJGGGASLProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.GVSJGGGASLProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GVSJGGGASLProyectoIPSDeleteClosure : GVSJGGGASLProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public GVSJGGGASLProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GVSJGGGASLProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public GVSJGGGASLProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.GVSJGGGASLProyectoIPS.TapizHasVentana.VentanaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.GVSJGGGASLProyectoIPS.TapizHasEstadoDeFin.EstadoDeFinDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.GVSJGGGASLProyectoIPS.TapizHasBoton.BotonDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.GVSJGGGASLProyectoIPS.TapizHasMenu.MenuDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.GVSJGGGASLProyectoIPS.TapizHasItemsMenu.ItemsMenuDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GVSJGGGASLProyectoIPSCopyClosure : GVSJGGGASLProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public GVSJGGGASLProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GVSJGGGASLProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public GVSJGGGASLProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

