//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "GVSJGGGASL_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"GVSJGGGASLProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID GVSJGGGASLProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GVSJGGGASLProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID GVSJGGGASLProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GVSJGGGASLProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewGVSJGGGASLProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GVSJGGGASLProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string GVSJGGGASLProyectoIPSPackageId = "ef91a6af-7888-4f47-bc06-1c183cd8f996";
		
		// Editor factory identifier
		public const string GVSJGGGASLProyectoIPSEditorFactoryId = "47d71fa4-cfd3-4123-8d15-58dea22efa6c";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string GVSJGGGASLProyectoIPSModelExplorerToolWindowId = "401241a0-7961-498f-b37e-8a4af91ef4e3";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string GVSJGGGASLProyectoIPSCommandSetId = "07cdc10b-5ad5-4dee-add6-11772993f1bb";
	}
}