//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "GVSJGGGASL_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"GVSJGGGASLProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID GVSJGGGASLProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GVSJGGGASLProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID GVSJGGGASLProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GVSJGGGASLProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewGVSJGGGASLProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GVSJGGGASLProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string GVSJGGGASLProyectoIPSPackageId = "978f62d7-25ba-4333-995b-bd65423e255b";
		
		// Editor factory identifier
		public const string GVSJGGGASLProyectoIPSEditorFactoryId = "ed987b9c-01e6-46db-a2ee-24aece88a9ad";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string GVSJGGGASLProyectoIPSModelExplorerToolWindowId = "ddee80ea-ea8c-4a06-b576-457f8f3d0a82";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.GVSJGGGASLProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string GVSJGGGASLProyectoIPSCommandSetId = "4810692c-f2d5-4a3b-a011-339ef15ab2e1";
	}
}